#!/usr/bin/env python3
"""
Example: ROS2 Service Integration

Demonstrates using FR5 robot through ROS2 services including:
- SetJointPosition service
- GripperControl service
- Service discovery and monitoring
"""

import sys
import os

print("=" * 70)
print("FR5 ROS2 Service Integration Example")
print("=" * 70)
print("\nThis example demonstrates ROS2 service usage with FR5 robot.\n")

print("Prerequisites:")
print("-" * 70)
print("1. Start the FR5 PyBullet simulation node:")
print("   Terminal 1: ros2 run fr5_pybullet_sim sim_node")
print()
print("2. Or use the tmux launch script:")
print("   cd /home/cflores18/fr5_ws/scripts")
print("   ./launch_with_tmux.sh sim")
print("-" * 70)
print()

print("ROS2 Service Commands:")
print("=" * 70)

print("\n1. List Available Services")
print("-" * 70)
print("Command:")
print("  ros2 service list")
print()
print("Expected output:")
print("  /gripper_control")
print("  /set_joint_position")
print("  [... other system services ...]")
print()

print("\n2. Get Service Type Information")
print("-" * 70)
print("Command:")
print("  ros2 service type /set_joint_position")
print("  ros2 service type /gripper_control")
print()
print("Expected output:")
print("  fr5_msgs/srv/SetJointPosition")
print("  fr5_msgs/srv/GripperControl")
print()

print("\n3. Call Set Joint Position Service")
print("-" * 70)
print("Move to home position (all zeros):")
print("Command:")
print("  ros2 service call /set_joint_position fr5_msgs/srv/SetJointPosition \\")
print("    \"{joint_positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]}\"")
print()
print("Move to specific position (degrees converted to radians):")
print("Command:")
print("  ros2 service call /set_joint_position fr5_msgs/srv/SetJointPosition \\")
print("    \"{joint_positions: [0.523, -0.523, 0.785, -1.047, 0.0, 0.523]}\"")
print()
print("Note: Values are in radians. Example conversions:")
print("  30° = 0.523 rad")
print("  45° = 0.785 rad")
print("  60° = 1.047 rad")
print("  90° = 1.571 rad")
print()

print("\n4. Call Gripper Control Service")
print("-" * 70)
print("Open gripper fully (100%):")
print("Command:")
print("  ros2 service call /gripper_control fr5_msgs/srv/GripperControl \\")
print("    \"{position: 100}\"")
print()
print("Close gripper completely (0%):")
print("Command:")
print("  ros2 service call /gripper_control fr5_msgs/srv/GripperControl \\")
print("    \"{position: 0}\"")
print()
print("Set gripper to 50% open:")
print("Command:")
print("  ros2 service call /gripper_control fr5_msgs/srv/GripperControl \\")
print("    \"{position: 50}\"")
print()

print("\n5. Monitor Joint States Topic")
print("-" * 70)
print("View real-time joint states:")
print("Command:")
print("  ros2 topic echo /joint_states")
print()
print("Expected output (sample):")
print("  header:")
print("    stamp:")
print("      sec: 1234567890")
print("      nanosec: 123456789")
print("  name:")
print("  - j1")
print("  - j2")
print("  - j3")
print("  - j4")
print("  - j5")
print("  - j6")
print("  position: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]")
print("  velocity: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]")
print("  effort: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]")
print()

print("\n6. Monitor TCP Pose Topic")
print("-" * 70)
print("View end-effector pose:")
print("Command:")
print("  ros2 topic echo /tcp_pose")
print()
print("Expected output (sample):")
print("  header:")
print("    stamp:")
print("      sec: 1234567890")
print("  pose:")
print("    position:")
print("      x: 0.5")
print("      y: 0.0")
print("      z: 0.4")
print("    orientation:")
print("      x: 0.0")
print("      y: 0.0")
print("      z: 0.0")
print("      w: 1.0")
print()

print("\n7. Python Client Example")
print("-" * 70)
print("Sample Python code to call services:")
print()
print("```python")
print("import rclpy")
print("from rclpy.node import Node")
print("from fr5_msgs.srv import SetJointPosition, GripperControl")
print()
print("rclpy.init()")
print("node = Node('fr5_client')")
print()
print("# Create service clients")
print("joint_client = node.create_client(SetJointPosition, '/set_joint_position')")
print("gripper_client = node.create_client(GripperControl, '/gripper_control')")
print()
print("# Wait for services")
print("joint_client.wait_for_service()")
print("gripper_client.wait_for_service()")
print()
print("# Move to position")
print("req = SetJointPosition.Request()")
print("req.joint_positions = [0.0, -0.523, 0.785, -1.047, 0.0, 0.0]")
print("future = joint_client.call_async(req)")
print("rclpy.spin_until_future_complete(node, future)")
print("response = future.result()")
print("print(f'Success: {response.success}, Message: {response.message}')")
print()
print("# Control gripper")
print("req = GripperControl.Request()")
print("req.position = 50  # 50% open")
print("future = gripper_client.call_async(req)")
print("rclpy.spin_until_future_complete(node, future)")
print("response = future.result()")
print("print(f'Success: {response.success}, Message: {response.message}')")
print()
print("node.destroy_node()")
print("rclpy.shutdown()")
print("```")
print()

print("\n8. Complete Pick-and-Place Sequence")
print("-" * 70)
print("Execute a complete pick-and-place using ROS2 services:")
print()
print("# 1. Open gripper")
print("ros2 service call /gripper_control fr5_msgs/srv/GripperControl \"{position: 100}\"")
print()
print("# 2. Move to approach")
print("ros2 service call /set_joint_position fr5_msgs/srv/SetJointPosition \\")
print("  \"{joint_positions: [0.0, -0.523, 0.785, -1.047, 0.0, 0.0]}\"")
print()
print("# 3. Move to pick")
print("ros2 service call /set_joint_position fr5_msgs/srv/SetJointPosition \\")
print("  \"{joint_positions: [0.0, -0.698, 1.047, -1.396, 0.0, 0.0]}\"")
print()
print("# 4. Close gripper")
print("ros2 service call /gripper_control fr5_msgs/srv/GripperControl \"{position: 30}\"")
print()
print("# 5. Lift")
print("ros2 service call /set_joint_position fr5_msgs/srv/SetJointPosition \\")
print("  \"{joint_positions: [0.0, -0.523, 0.785, -1.047, 0.0, 0.0]}\"")
print()
print("# 6. Move to place")
print("ros2 service call /set_joint_position fr5_msgs/srv/SetJointPosition \\")
print("  \"{joint_positions: [0.785, -0.523, 0.785, -1.047, 0.0, 0.785]}\"")
print()
print("# 7. Release")
print("ros2 service call /gripper_control fr5_msgs/srv/GripperControl \"{position: 100}\"")
print()
print("# 8. Return home")
print("ros2 service call /set_joint_position fr5_msgs/srv/SetJointPosition \\")
print("  \"{joint_positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]}\"")
print()

print("=" * 70)
print("ROS2 Integration Features:")
print("  ✓ SetJointPosition service for motion control")
print("  ✓ GripperControl service for gripper operations")
print("  ✓ /joint_states topic publishing (10Hz)")
print("  ✓ /tcp_pose topic publishing (10Hz)")
print("  ✓ Service-based architecture")
print("  ✓ Compatible with ROS2 Humble/Jazzy")
print("=" * 70)
print()
print("Tip: Use the tmux launch script for organized multi-pane visualization:")
print("     cd /home/cflores18/fr5_ws/scripts && ./launch_with_tmux.sh sim")
print("=" * 70)
